backend/.gitignore, backend/get_lunch_info.py, backend/main.py, frontend/app/[locale]/page.tsx, frontend/components/RegionChanger.tsx, frontend/locales/en/translation.json, frontend/locales/fi/translation.json
Add region parameter to /restaurants. Also adds scraper for ståhlberg in tampere.
Need to add something in the frontend to configure region in the future
Related to #35
=> feat: add region filter and ståhlberg scraper

backend/get_lunch_info.py
- Add error handling to Queem for Saturday and Sunday.
=> Add error handling to queem

backend/get_lunch_info.py
- The previous PR was not a proper fix to the issue.
=> Fix queem error handling

backend/get_lunch_info.py
- In case of issues just return the fallback menu.
Before:
After:
=> Add general error handling

.github/workflows/deploy.yml
- Add workflow to deploy frontend and backend changes when pushed to the main branch.
- We can test this using your latest PR.
=> Add CD workflow using github actions

frontend/app/[locale]/[region]/page.tsx, frontend/app/[locale]/layout.tsx, frontend/app/[locale]/page.tsx, frontend/components/RegionChanger.tsx, frontend/lib/restaurants.ts, frontend/next.config.ts, frontend/package-lock.json, frontend/package.json, frontend/tsconfig.json, frontend/utils/constants.ts
Using searchParams for regions broke our static site generation, so new API requests were made on every page load. Let's include the region in the path instead, eg `/kamppi` or `/tampere`.
The index page will still show the default region (kamppi).
=> fix: static site generation with regions

.github/workflows/deploy.yml
Looks like the deploy frontend job was incorrectly indented. My bad for not noticing 😅
=> fix: CI job indent

backend/get_lunch_info.py
Add Valssi restaurant in Tampere.
Related to #35
=> feat: add valssi in tampere

backend/get_lunch_info.py, backend/main.py, frontend/app/[locale]/[region]/page.tsx, frontend/assets/icons/graduation-cap.svg, frontend/components/RestaurantCard.tsx, frontend/locales/en/translation.json, frontend/locales/fi/translation.json
Adds icon for student cantines next to the restaurant name. We could add a filter for these in the future also.
=> feat: add student cantine icon

frontend/.eslintrc.json, frontend/app/[locale]/[region]/page.tsx, frontend/app/[locale]/layout.tsx, frontend/app/i18n.ts, frontend/app/robots.txt, frontend/components/LanguageChanger.tsx, frontend/i18nConfig.ts, frontend/package-lock.json, frontend/package.json, frontend/utils/helpers.ts
This PR fixes some SEO issues.
=> fix: seo issues with canonical link and robots

frontend/app/[locale]/layout.tsx
I think this one looks pretty good. We can try different ones later today.
Closes #67
=> feat: add roboto font

README.md, docs/custom-domain.md, frontend/app/[locale]/[region]/page.tsx, frontend/app/[locale]/layout.tsx
- Add a doc about adding a custom domain. This can be useful later if we change the hosting platform.
- Small updates to README.md.
- We have our own domain working 🥳
=> Chore: Add docs

backend/get_lunch_info.py
This fixes the valssi scraper. The dates on the site are formatted like '7.11.' while we had an extra zero '07.11.' in the code.
=> fix: valssi restaurant scraper

README.md, frontend/components/Footer.tsx, frontend/locales/en.ts, frontend/locales/fi.ts
- Created an email address for us. There were some issues in forwarding emails to gmail, which I would like to do to not have to look into this email so often. We can add your emails in the forward list too, but let's test that forwarding does not block sending emails to this address.
- Add the contact information to the footer.
- We could also add it as contact(at)lunssi.fi but I would not mind this email "leaking". We can do that if it looks cooler to you 😄 
- Arranged locales `.ts` files alphabetically.
=> Feature: add a contact email

backend/get_lunch_info.py
Fix que em scraper by scraping also menu pdf url. This way we wont have to update them manually in the future.
=> fix: que em scraper by scraping menu pdf url

frontend/app/robots.txt, frontend/app/sitemap.ts
Add sitemap.xml. Could help improve SEO.
=> feat: add sitemap.xml

backend/get_lunch_info.py
=> feat: add restaurant Karljohan

backend/get_lunch_info.py
Kansis scraper is currently broken, at least for English. This should work for both Finnish and English
=> fix: kansis scraper

backend/scrapers/__init__.py, backend/scrapers/puisto.py
- Add Puisto restaurant based on user feedback.
Closes #146
=> Add puisto

backend/scrapers/kansis.py
The Kansis menu list no longer appears to be using h3 elements for the headings, which breaks this scraper. This fix should work regardless of what element is used for the headers.
=> fix: kansis menu scraper

backend/main.py, backend/scrapers/base.py, frontend/app/[locale]/[region]/page.tsx, frontend/components/RestaurantCard.tsx
- Make the restaurant name a clickable link that leads to the restaurant menu website.
- Make variable names more consistent across front and back and reorder alphabetically.
Looks the same at first:
When hovering over:
Leads to:
=> Feat: Make restaurant name clickable

docs/contact-mail.md, docs/google-analytics.md
=> chore: update documentation

backend/scrapers/kansis.py
This will support both "Monday, August 4." and "Monday, 4.8." formats
=> fix: kansis english scraper
